// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.778
package contact

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func ContactForm() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<form id=\"contactForm\" class=\"max-w-xl mx-auto\" hx-post=\"/api/contact\" hx-trigger=\"submit\" hx-target=\"#successMessage\" hx-swap=\"textContent\"><!-- Name Input --><div class=\"mb-4\"><label for=\"name\" class=\"block text-gray-700 font-bold mb-2\">Name</label> <input type=\"text\" id=\"name\" name=\"name\" class=\"w-full px-3 py-2 border rounded-md focus:outline-none focus:border-cyan-500\" required></div><div class=\"mb-4 flex flex-wrap -mx-2\"><div class=\"w-full md:w-1/2 px-2 mb-4 md:mb-0\"><label for=\"email\" class=\"block text-gray-700 font-bold mb-2\">Email</label> <input type=\"email\" id=\"email\" name=\"email\" class=\"w-full px-3 py-2 border rounded-md focus:outline-none focus:border-cyan-500\"></div><div class=\"w-full md:w-1/2 px-2\"><label for=\"phone\" class=\"block text-gray-700 font-bold mb-2\">Phone</label> <input type=\"tel\" id=\"phone\" name=\"phone\" class=\"w-full px-3 py-2 border rounded-md focus:outline-none focus:border-cyan-500\"></div></div><!-- Message Textarea --><div class=\"mb-4\"><label for=\"message\" class=\"block text-gray-700 font-bold mb-2\">Message</label> <textarea id=\"message\" name=\"message\" rows=\"4\" class=\"w-full px-3 py-2 border rounded-md focus:outline-none focus:border-cyan-500\"></textarea></div><!-- Submit Button --><div class=\"mb-6\"><button type=\"submit\" class=\"w-full bg-cyan-500 text-white py-2 px-4 rounded-md hover:bg-cyan-700 focus:outline-none focus:shadow-outline-cyan active:bg-cyan-800\">Submit</button></div></form><div id=\"successMessage\" class=\"container mx-auto text-center text-cyan-600 font-bold\"><!-- Thank you for reaching out! I will get back to you soon. --></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
